# Generated by Django 5.2.7 on 2025-10-18 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('predicted_category_id', models.PositiveIntegerField(help_text='Primary category for this segment')),
                ('characteristics', models.JSONField(default=dict, help_text='Store segment characteristics')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='NA', max_length=100)),
                ('last_name', models.CharField(default='NA', max_length=100)),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('biography', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.ImageField(default='profile_pics/placeholder.jpg', upload_to='profile_pics')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age for AI prediction', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('occupation', models.CharField(blank=True, choices=[('student', 'Student'), ('professional', 'Professional'), ('business', 'Business Owner'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20)),
                ('education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD')], max_length=20)),
                ('income_range', models.CharField(blank=True, choices=[('low', 'Below $2,000'), ('medium', '$2,000 - $5,000'), ('high', '$5,000 - $10,000'), ('very_high', 'Above $10,000')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='Singapore', max_length=100)),
                ('predicted_category_id', models.PositiveIntegerField(blank=True, help_text='AI predicted preferred category ID', null=True)),
                ('prediction_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('prediction_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.PositiveIntegerField(help_text='Category ID for preference tracking')),
                ('preference_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category_id')},
            },
        ),
    ]
