# Generated by Django 5.2.7 on 2025-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Student', 'Student'), ('Retired', 'Retired'), ('Unemployed', 'Unemployed')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_children',
            field=models.BooleanField(default=False, help_text='Whether user has children'),
        ),
        migrations.AddField(
            model_name='profile',
            name='household_size',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of people in household', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_income_sgd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income in SGD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Sales', 'Sales'), ('Service', 'Service'), ('Admin', 'Admin'), ('Education', 'Education'), ('Skilled Trades', 'Skilled Trades'), ('Other', 'Other')], max_length=20),
        ),
    ]
