# Generated by Django 5.2.7 on 2025-10-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderreturn_customernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped Back'), ('received', 'Received'), ('refunded', 'Refunded'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
