# Generated by Django 5.2.7 on 2025-10-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderreturn_closed_at_orderreturn_shipped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('order_cancelled', 'Order Cancelled'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_shipped', 'Return Shipped'), ('return_received', 'Return Received'), ('refund_processed', 'Refund Processed'), ('return_closed', 'Return Closed')], max_length=20),
        ),
    ]
