# Generated by Django 5.2.7 on 2025-10-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_customernotification_notification_type'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('loyalty_points', 'Loyalty Points'), ('loyalty_reward', 'Loyalty Reward'), ('promo_code', 'Promo Code')], max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_used', models.PositiveIntegerField(default=0, help_text='Loyalty points used for this discount')),
                ('description', models.CharField(max_length=200)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='checkout.cart')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltyreward')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
